spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_n1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
  application:
    name: seata-n1
  cloud:
    nacos:
      service-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: true
    alibaba:
      seata:
        txServiceGroup: my_test_tx_group

server:
  port: 8061

seata:
  registry:
    type: nacos
    nacos:
      serverAddr: localhost:8848 #seata所在的nacos地址
      application: seata-server #seata的服务名
      username: nacos
      password: nacos
      group: SEATA_GROUP #seata所在的组
  config: #配置seata的配置中心 可以读取一些关于seata client的一些配置
    type: nacos
    nacos:
      serverAddr: localhost:8848 #seata所在的nacos地址
      application: seata-server #seata的服务名
      username: nacos
      password: nacos
      group: SEATA_GROUP #seata所在的组